baseurl: "https://www.runhangshu.com/"
languageCode: "en-us"
title: "Runhang Shu | 舒润航"
theme: "hugo-ivy"
disqusShortname: "https-www-runhangshu-com" 
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩" 
rssLimit: 100

permalinks:
  cn: "/:sections/:year/:month/:slug/"
  en: "/:sections/:year/:month/:slug/"

menu:
  main:
    - name: "About"
      url: "/about.md"
      weight: 1
    - name: "Bioinformatics"
      url: "/en/"
      weight: 2
    - name: "严肃扯谈"
      url: "/cn/"
      weight: 3
    - name: "CV"
      url : "https://uflorida-my.sharepoint.com/:w:/g/personal/r_shu_ufl_edu/ESztl3T6QWJHuW6bke6BodEBaM05Gy3oLaK61wHJcEAAZQ" 
      weight: 4
    - name: "TWITTER"
    url : "https://twitter.com/Runhang1"
    weight: 5
    
  en:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/en/about/"
      weight: 2
    - name: "中文"
      url: "/cn/"
      weight: 5
  cn:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/about.md"
      weight: 2
    - name: "日志"
      url: "/cn/"
      weight: 3
    - name: "English"
      url: "/en/"
      weight: 4
 

params:
  description: "Personal website of Runhang Shu; 舒润航的个人网站"
  footer: "&copy; [Runhang Shu](/) 2019 - 2021"
  disqusURL: "https://www.runhangshu.com"
  customJS:
    - "js/fix-toc.js"
    - "js/center-img.js"
    - "js/right-quote.js"
    - "js/no-highlight.js"
    - "js/fix-footnote.js"
    - "js/math-code.js"
    - "js/external-link.js"
    - "js/alt-title.js"
    - "js/header-link.js"
  githubContentURL: "https://github.com/RunhangShu/RunhangWebsite/tree/main/content"
  twitterImage: "/images/logo.jpg"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "9.12.0"
  highlightjsCDN: "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"

  logo:
    en:
      img: "/images/logo.jpg"
      url: "/"
      alt: "Runhang Shu"
      tag: ""


  author:
    en: "Runhang Shu"
    cn: "舒润航"
    animation: ""

  lang:
    edit:
      cn: "编辑"
    license:
      cn: "版权"
    subscribe:
      cn: "订阅"

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false

markup:
  goldmark:
    renderer:
      unsafe: true
